terraform/development/main.tf, terraform/modules/database/output.tf, terraform/modules/database/rds.tf, terraform/modules/database/secrets.tf, terraform/modules/s3/output.tf, terraform/modules/services/forecast/README.md, terraform/modules/services/forecast/cloudwatch.tf, terraform/modules/services/forecast/ecs.tf, terraform/modules/services/forecast/iam.tf, terraform/modules/services/forecast/schedule-iam.tf, terraform/modules/services/forecast/schedule.tf, terraform/modules/services/forecast/variables.tf, terraform/modules/services/nwp/README.md
add forecast module
- ecs task definition
- iam role
- aws scheduled task
Fixes #
ran terraform apply and forecast task runs and saves predictions to the database
=> add forecast module

terraform/modules/services/pv/ecs.tf, terraform/modules/services/pv/iam.tf, terraform/modules/services/pv/variables.tf
Give PV consumer access to forecast database
terraform validation and plan
=> update pv to use forecast database

terraform/development/main.tf, terraform/modules/services/forecast/iam.tf, terraform/modules/services/forecast/variables.tf
add read access to s3 for forecast
Fixes #
=> allow forecasdt to read satellite s3

terraform/modules/services/gsp/schedule.tf
Run GSP consumer also at 20 and 50 minutes past the hour
Fixes #https://github.com/openclimatefix/nowcasting_infrastructure/issues/97
=> add 20 and 50 calls on GSP data

terraform/modules/services/api/eb.tf
Reduce api cloudwatch to 7 days. 
We need to think of a different way to log the number of hits to the api
Fixes #
CI
=> reduce api cloudwatch time to 7 days

terraform/modules/database/rds.tf
To fix the broken API last week I upped the allocated storage on the db, manually using the AWS console.
This implements that increaase officially using terraform.
=> Increase storage of forecast db (officially this time)

terraform/modules/services/api_pvsite/docker-compose.yml
The docker as built by https://github.com/openclimatefix/pv-site-api now uses poetry.
=> Update the pv-site-api command to use poetry

terraform/pvsite/production/main.tf
This is a temporary measure until we make it run faster.
=> Make the pvsite forecast run every 2 hours

terraform/modules/storage/database-pair/rds.tf, terraform/modules/storage/postgres/rds.tf
add parameter group for each database, 
- random_page_cost=1.1. The deafult is 4, but because we are using gp3 fast storage, we should encourage the databse to read more things in storage
Fixes #186 
CI plans
=> Rds random page costs

terraform/modules/storage/database-pair/rds.tf, terraform/modules/storage/postgres/rds.tf, terraform/nowcasting/development/provider.tf, terraform/nowcasting/production/provider.tf, terraform/pvsite/development/provider.tf, terraform/pvsite/production/provider.tf
Hopefully resolves the IOPS issue with GP3 storage. If this doesn't work, then we might have to use the community RDS module.
=> Bump AWS provider to 4.47.0

terraform/modules/services/gsp/ecs.tf, terraform/modules/services/gsp/schedule.tf
Adjust GSP pulling times to UTC
- National at 10.45 UTC
- GSP at 11.30 UTC
Fixes #219 
- looked at GSP locally, and saw when it was pulled
- CI tests
=> run all GSP d+1 in UTC

terraform/nowcasting/production/main.tf, terraform/pvsite/production/main.tf
Currently we are implementing two instances of dev/prod environment separation: in directory structure, and in branch. Whilst this is backed up by valid reasoning, it results in a lack of immediate clarity around the real source of truth for our TF instances, for instance:
- To see what's actively deployed in AWS development, does you look in `development/main.tf` on the main branch or the development branch?
- How do you quickly tell what changes in the development branch are present in main if the commit histories never line up?
The directory-based separation has a clear logical reasoning: by having a `development/main.tf` and a `production/main.tf` we are able to deploy different services to our production and development environments. This is important for being able to spin up …
=> Sunset development branch

terraform/modules/services/pv/schedule.tf
Update PV Consumer to run 1 minute earlier
Helps fix https://github.com/openclimatefix/nowcasting_forecast/issues/199
CI terrafrom tests
=> update PV Consumer time to run 1 minute earlier

terraform/modules/services/forecast_generic/ecs.tf, terraform/modules/services/forecast_generic/variables.tf, terraform/nowcasting/development/main.tf
- change pvnet 2.0 to log level to INFO
CI terraform checks
=> ad option for loglevel in forecast generic

terraform/nowcasting/production/main.tf, terraform/nowcasting/production/variables.tf
Add PVnet 2.0 to production, this wont effect the output, but just gets int running every 30 mins
Fixes #
Ci tests, and run on development
=> ad pvnet2 to production

terraform/modules/services/metrics/schedule-iam.tf, terraform/modules/services/metrics/schedule.tf
- remove metric scheudle
- change pvnet and national_xg to run once a day. Airflow does the rest. Need to move sites over to airflow
Fixes #
CI tests
=> remove metrics schedule

terraform/modules/services/airflow/dags/forecast-site-dag.py
change site level dag to look 25 hours in the past. This means the site db clean up will run
CI tests, similar to other dags with 24 hours
=> change site to 25 hours, so site db clean up works

terraform/modules/storage/database-pair/rds.tf, terraform/modules/storage/postgres/rds.tf
**Feature: Enable Automated Backups for RDS Instance**
This pull request adds functionality to enable automated backups for the RDS instance using Terraform. Automated backups are essential for data recovery and disaster resilience.
**Changes Made:**
- Introduced the 'backup_retention_period' attribute within the aws_db_instance resource block.
- Configured backup retention period to 7 days for ensuring adequate data retention.
**Why this is needed:**
Automated backups provide a safety net against data loss and system failures. This enhancement improves our infrastructure's reliability and resilience.
**Additional Notes:**
- Tested locally and verified proper integration with existing configurations.
- Documentation has been updated to reflect the new configuration option.
Fixes #90
=> Set backup_retention_period to 7 days to enable automated backups

terraform/modules/services/forecast_generic/ecs.tf, terraform/modules/services/forecast_generic/variables.tf, terraform/modules/services/internal_ui/docker-compose.yml, terraform/modules/services/internal_ui/eb.tf, terraform/modules/services/internal_ui/variables.tf, terraform/modules/services/metrics/ecs.tf, terraform/modules/services/metrics/variables.tf, terraform/nowcasting/development/main.tf
- add to forecast
- add to metrics
- add to ocf dashboard
only change this for development
Helpes with https://github.com/openclimatefix/pvnet_app/issues/15
CI tests
=> Pvnet gsp sum

terraform/airflow/production/main.tf
Implement change to module specified in commit [84db064](https://github.com/openclimatefix/ocf-infrastructure/commit/84db0645467a4de90baaf8fd7964ebdff475a5e7) to the production airflow instance
=> Update airflow in production to use module version 84db064

terraform/airflow/development/main.tf, terraform/nowcasting/development/main.tf, terraform/nowcasting/development/variables.tf
Move airflow over to nowcasting platform
I left a TODO because I didnt want to change the actual airflow module
Note a new password would get made, so we would have to update where this is stored
Needed to add `ecs_security_group` to variables
Helps with #302 
Terraform run on CI
=> move airflow to nowcasting

terraform/modules/services/forecast_generic/ecs.tf
add env var to forecast generic, this is needed for pvnet when regridding the data
[Fixes #](https://github.com/openclimatefix/ocf-infrastructure/issues/320)
CI tests
=> add env variable for pvnet. This is needed when importing

terraform/nowcasting/production/main.tf, terraform/nowcasting/production/variables.tf
- add airflow intergration to slack
- add variable `airflow_conn_slack_api_default` to production terraform
- add env var to airflow instance
- adjutsed dags to send message on failure
Fixes #350 
tested this on dev
=> add airflow intergation to slack

terraform/modules/services/airflow/dags/forecast-gsp-dag.py, terraform/modules/services/airflow/dags/forecast-national-dag.py
Update dags task-ids for forecast
Fix pvnet-2 task id name (it was labelled as pvnet 1)
CI tests
=> update dags task ids for forecast

terraform/modules/services/airflow/dags/forecast-national-dag.py
increase national forecast to 2 retries. This cover the bug that the nwp data is being made at the same time
=> retry national forecast 2

terraform/modules/storage/postgres/rds.tf
This pull request addresses issue #383 by upgrading the RDS PostgreSQL engine to version 16.1.
File: **./terraform/modules/storage/postgres/rds.tf**
```
-  engine_version               = "15.5"
+  engine_version               = "16.1"
```
Fixes #383
- [*] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [*] I have performed a self-review of my own code
=> Fixes upgrade rds postgres to 16.1 #383

terraform/modules/networking/ec2_bastion/ec2.tf
This pull request to address a deprecation warning related to the usage of the vpc attribute in the aws_eip resource, the warning suggests using the domain attribute instead.
**Changes Made:**
- Replaced _vpc = "true"_ in _aws_eip_ resource, using _domain = "vpc"_
**Why this is needed:**
The pull request aims to update the Terraform code to align with the latest recommendations and resolve the deprecation warning.
Please review the changes, and if everything looks good, feel free to merge it. If you have any questions or concerns, please don't hesitate to reach out.
Thanks,
Pedro
Fixes #421 
- [*] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [*] I have performed a self-review of my own code
- [*] I have checked my …
=> Fixes terraform depreciation on vpc -> domain #421

terraform/nowcasting/development/main.tf
This PR resolves https://github.com/openclimatefix/ocf-infrastructure/issues/469
In the `nowcasting/development/main.tf` file, I have made changes to the `nwp-national` and `data-national` service as instructed in the issue
Fixes #
I was not able to `terraform validate` to run the tests, if possible can someone guide me a bit more on how to run the tests
=> chore: renaming nwp service to include metoffice

terraform/nowcasting/development/README.md, terraform/nowcasting/production/README.md
Update the terraform READMEs to include the GSP Consumer component and update airflow dags links which were broken
=> Update terraform readme

.gitignore, terraform/modules/services/airflow/dags/india/forecast-site-dag.py, terraform/modules/services/airflow/dags/india/nwp-dag.py, terraform/modules/services/airflow/dags/india/runvnl-data-dag.py, terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py, terraform/modules/services/airflow/dags/uk/forecast-national-dag.py, terraform/modules/services/airflow/dags/uk/forecast-site-dag.py, terraform/modules/services/airflow/dags/uk/gsp-dag.py, terraform/modules/services/airflow/dags/uk/nwp-dag.py, terraform/modules/services/airflow/dags/uk/pv-dag.py, terraform/modules/services/airflow/dags/uk/satellite-dag.py
the `datetime.utcnow()` method is considered deprecated in modern Python versions, and it's recommended to use the more explicit `datetime.now(tz=datetime.timezone.utc)` instead. The `utcnow()` method is still functional, but it's considered less clear and less timezone-aware than the alternative. I have thus replaced the deprecated method with the newer one
Fixes #
#528
=> added timezone aware datetime function

terraform/modules/services/ecs_task/ecs.tf
ECS tasks currently shared a mounted volume which was causing errors in multiple consumer tasks defintiions. This isolates volumes between containers of the same task definition.
=> fix(ecs-task): Prevent overlapping cache errors in ECS tasks

terraform/modules/services/airflow/dags/uk/gsp-dag.py, terraform/modules/services/airflow/dags/uk/nwp-dag.py, terraform/modules/services/airflow/dags/uk/satellite-dag.py
Add bash operater to hit api after consumer has finished. This is for
- gsp
- nwp
- satellite
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/337
Deploy one of the dags manually and checked it worked
=> add dags for updating data

terraform/nowcasting/production/main.tf
Upgrade airflow, so dags hit api endpoint when nwp, sat, and gsp consumer are complete
Give API read access to s3 buckets
[Fixes #](https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/337)
Tested on dev
=> upgrade airflow, give api acess to nwp and sat buckets

terraform/nowcasting/development/README.md, terraform/nowcasting/production/README.md, terraform/nowcasting/production/main.tf, terraform/nowcasting/production/variables.tf
- add pvnet day ahead to production
- udpate readme.md in both development and production
- (add forecast_pvnet_day_ahead_docker_version to variables in terraform)
CI tests
=> add pnvet day head +upgrade airflow + docs

terraform/india/development/main.tf, terraform/modules/services/ecs_task/ecs.tf, terraform/modules/services/ecs_task/variables.tf, terraform/nowcasting/development/main.tf
GFS container runs out of disk space. This enables it to be specified.
=> fix(ecs-task): Enable specification of ephemeral storage size

terraform/modules/services/airflow/dags/india/forecast-site-dag.py
Change back to run forecast at 0 min, it actually made more errors than I thought it would solve
Moving it back to what it was
=> run forecast at 0 min again

terraform/modules/services/airflow/dags/india/forecast-site-dag.py
Dont run india forecast at 7,8,19 and 29
This is due to https://github.com/openclimatefix/india-forecast-app/issues/86
Ci test
=> dont run india forecast at 7,8,19,20

terraform/india/development/main.tf
Add sentry env vars to RUVNL consumer
Helps wtih #540 
CI tests
=> add sentry env vars

terraform/nowcasting/production/main.tf, terraform/nowcasting/production/variables.tf
Add PVnet ecmwf only task on production
Update airflow on production to run this task
Helps with https://github.com/openclimatefix/uk-pvnet-app/issues/123
- CI test
- tested on dev, and it works
=> add pvnet ecmwf + update airflow to run it

terraform/modules/services/forecast_generic/ecs.tf, terraform/modules/services/forecast_generic/variables.tf
add use-data-sampler to forecast generic, set to default
CI tests
=> add use data sampler to forecast generic

terraform/modules/services/forecast_generic/ecs.tf
Fixes `KeyError: 'NWP_MO_GLOBAL_ZARR_PATH'` seen in cloudwatch.
=> Add NWP_MO_GLOBAL_ZARR_PATH to forecast_generic

terraform/india/production/main.tf, terraform/india/production/variables.tf
Add autho to india dashboard app
#700 
CI tests
=> add variables for indai pro analysis dashboard

terraform/nowcasting/development/main.tf
Change National xg to use ecs task
CI tests
=> change national forecast to ecs task

terraform/modules/services/airflow/dags/uk/dayafter-dag.py, terraform/modules/services/airflow/dags/uk/pvlive-dag.py, terraform/nowcasting/development/main.tf
- update to pvlive docker
- update ecs tasks
- update dags
Helps with #709
CI tests
=> Pvlive Consumer

terraform/india/development/main.tf, terraform/india/development/variables.tf, terraform/modules/services/airflow/dags/india/nwp-dag.py
Change GFS to new consumer
#697
=> change to new gfs nwp-consumer

terraform/nowcasting/production/main.tf, terraform/nowcasting/production/variables.tf
Update new nwp-consumer for ECMWF
Already updated dashbaord and PVnet app, to 2.4.19 and 2b68542
#697 
- CI tests
- tested on dev
=> update ecmwf to new nwp-consumer

terraform/modules/services/airflow/dags/uk/nwp-dag.py
Look at .zattrs when looking at when the nwp was last updated
Fixes https://github.com/openclimatefix/ocf-infrastructure/issues/740
=> use .zattrs when looking nwp has been updated

terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
Correct dag spelling for PVNet ECMWF
Helps [openclimatefix/ocf-infrastructure/issues/748]
Just a simple spelling fix.
@peterdudfield It seemed easy, so I am opening a PR. Let me know if any changes are required. Thanks.
=> spelling corrected for PVNet ECMWF

terraform/modules/services/airflow/dags/india/forecast-site-dag.py, terraform/modules/services/airflow/dags/india/nwp-dag.py, terraform/modules/services/airflow/dags/india/runvnl-data-dag.py, terraform/modules/services/airflow/dags/india/satellite-dag.py, terraform/modules/services/airflow/dags/uk/dayafter-dag.py, terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py, terraform/modules/services/airflow/dags/uk/forecast-national-dag.py, terraform/modules/services/airflow/dags/uk/forecast-site-dag.py, terraform/modules/services/airflow/dags/uk/nwp-dag.py, terraform/modules/services/airflow/dags/uk/pv-dag.py, terraform/modules/services/airflow/dags/uk/pvlive-dag.py, terraform/modules/services/airflow/dags/uk/satellite-dag.py, terraform/modules/services/airflow/iam.tf
Get cloudwatch logs, when looking at ariflow
#756 
- tested it locally, by uploading a file
- CI test
=> add aws cloudwatch logs to airflow

terraform/india/production/main.tf
save batches in s3 bucket
Helps with #697 as cane compare batches and see what is different
- tested on dev
- Ci tests
=> save batches for india foreacst

terraform/modules/services/airflow/dags/uk/forecast-national-dag.py, terraform/nowcasting/development/main.tf, terraform/nowcasting/development/variables.tf
- add ECS task for NESO solar forecast consumer
- add DAG to pull this data once an hour
#702 
Need https://github.com/openclimatefix/neso-solar-consumer/pull/33 before deploying
CI tests,
=> add ecs task and dag for neso foreacst

terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
Add warning message if PVnet fails. 
#749 
CI tests, but will need to test this on dev.
=> add a warning message, when pvnet fails

terraform/modules/services/airflow/dags/india/elasticbeanstalk.py, terraform/modules/services/airflow/dags/india/forecast-site-dag.py, terraform/modules/services/airflow/dags/india/nwp-dag.py, terraform/modules/services/airflow/dags/india/runvnl-data-dag.py, terraform/modules/services/airflow/dags/india/satellite-dag.py, terraform/modules/services/airflow/dags/uk/cloudcasting-dag.py, terraform/modules/services/airflow/dags/uk/dayafter-dag.py, terraform/modules/services/airflow/dags/uk/elasticbeanstalk.py, terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py, terraform/modules/services/airflow/dags/uk/forecast-national-dag.py, terraform/modules/services/airflow/dags/uk/forecast-site-dag.py, terraform/modules/services/airflow/dags/uk/nwp-dag.py, terraform/modules/services/airflow/dags/uk/pv-dag.py, terraform/modules/services/airflow/dags/uk/pvlive-dag.py, terraform/modules/services/airflow/dags/uk/satellite-dag.py, terraform/modules/services/airflow/dags/utils/slack.py
Add airflow warning messages to all services
CI tests + deployed on dev
=> Airflow warning messages

terraform/india/production/main.tf
Updated the HISTORY environment variable from 60 to 75 minutes for satellite forecasts.  
Fixes #772
=> Set HISTORY=75 minutes for satellite forecast

terraform/modules/services/airflow/dags/uk/cloudcasting-dag.py, terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py, terraform/modules/services/airflow/dags/uk/forecast-national-dag.py, terraform/modules/services/airflow/dags/uk/forecast-site-dag.py, terraform/modules/services/airflow/dags/uk/nwp-dag.py, terraform/modules/services/airflow/dags/uk/pv-dag.py, terraform/modules/services/airflow/dags/uk/satellite-dag.py
Update warning messages on airflow
Ci tests
=> spelling and grammer

terraform/nowcasting/production/main.tf
Removing forecast genertic on national-xg and pvsite forecast
Copied from dev
=> change foreast_generic, on national-xg and pvsite forecast

terraform/modules/services/airflow/dags/uk/satellite-dag.py
pipeline will check both the 5-minute and 15-minute satellite files each run, and will fail early and alert Slack if one is missing
Fixes #764
=> 15 min filecheck added

terraform/modules/services/airflow/dags/india/nwp-dag.py, terraform/modules/services/airflow/dags/uk/nwp-dag.py
only let once task of determine_latest_zarr_ecmwf run at once by setting max_active_runs = 1 both in uk and india code.
Fixes #
I need more insights on how to test this
=> only let one task of determine_latest_zarr_ecmwf run at once.

terraform/nowcasting/development/main.tf
Since https://github.com/openclimatefix/uk-pvnet-app/pull/202, the uk-pvnet-app has changed container registry to github.
=> chore(forecast): Move pvnet to use GHCR

terraform/modules/services/airflow/dags/uk/pvlive-dag.py
changed the error message to 
```
"This is needed for the adjuster in the Forecast."
"No out of office hours support needed."
```
Fixes #
=> changed pvlive error message to a warning

terraform/nowcasting/development/main.tf, terraform/nowcasting/production/main.tf
This pull request addresses the issue of duplicate environment variables in the NWP consumer configuration for both development and production environments. The changes remove redundant entries for SENTRY_DSN and LOGLEVEL in the container-env_vars section of the Terraform configuration files.
Fixes #810
=> remove duplicate env vars in nwp consumer

terraform/nowcasting/development/main.tf
> For UK API **`v1.5.75`**
Update start command as the `src` module of the UK National API has now been renamed to `nowcasting_api`, so currently the dev API can't start 😅 
This is how it runs locally and through docker now.
=> update api start command after module rename

terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py, terraform/nowcasting/development/main.tf, terraform/nowcasting/production/main.tf
Add the new env var `RAISE_MODEL_FAILURE` for uk-pvnet-app (see [this PR](https://github.com/openclimatefix/uk-pvnet-app/pull/283) for details).
I have set `RAISE_MODEL_FAILURE="critical"` for both prod and dev. I think this is a good balance. We will only be notified by slack if one or more of the critical models does not run. 
On dev we are allowing the extra models to fail silently, but since they are only for monitoring purposes I think this is fine and we can pick that up from the internal analysis dashboard
=> Add env var for new pvnet app version

terraform/nowcasting/production/main.tf
Change UK production to 2 ec2 machines running the API. This gives extra reliances incase API goes down. 
note: Caching is per ec2 machine, so it could lead to a increase in data load on the database
#863
=> change to 2 apis
