- terraform/README.md
- terraform/modules/database/rds.tf
Automatically expands RDS storage.
Fixes #23 
> Automatically expands RDS storage

- terraform/modules/s3/s3.tf
Adds Satellite consumner S3 bucket
Fixes #36
> Add Sat TF file

- terraform/modules/database/rds.tf
> postgres db upgrade 13.4 to 14.1

- terraform/development/main.tf
- terraform/modules/database/iam.tf
- terraform/modules/database/output.tf
- terraform/modules/database/rds.tf
- terraform/modules/database/secrets.tf
add pv rds database
Fixes #38 
- TODO deploy to development
> add rds database

- local-stack/docker-compose.yml
- local-stack/tests/test_pv.py
Update pv consumer to load not the main filename
Fixes #60 
normal unittests + ran locally
> add filename to pv service

- local-stack/tests/test_gsp.py
> dummy commit

- local-stack/tests/test_gsp.py
- terraform/modules/services/gsp/schedule.tf
> fake commit

- terraform/development/main.tf
- terraform/development/variables.tf
- terraform/modules/services/data_visualization/README.md
- terraform/modules/services/data_visualization/docker-compose.yml
- terraform/modules/services/data_visualization/eb.tf
- terraform/modules/services/data_visualization/iam.tf
- terraform/modules/services/data_visualization/s3.tf
- terraform/modules/services/data_visualization/security_group.tf
- terraform/modules/services/data_visualization/variables.tf
add data vis module to elastic beanstalk
> Add data vis

- terraform/modules/services/api/s3.tf
> remove resource "aws_s3_bucket_acl"

- terraform/development/main.tf
- terraform/modules/services/forecast/iam.tf
- terraform/modules/services/forecast/variables.tf
add pv database secret to forecast
Fixes #
> add pv secret to forecast

- terraform/modules/services/data_visualization/eb.tf
add satellte aws filename to data vis
Fixes #
> add SATELLITE_AWS_FILENAME to data vis

- terraform/development/main.tf
- terraform/modules/s3/iam.tf
- terraform/modules/s3/output.tf
let the forecast write to the ml s3 bucket
Fixes #
> let forecast wrie to s3 bucket

- terraform/modules/services/forecast/ecs.tf
Update forecast to use CNN model
Fixes #
Ran it manually on AWS, making a new task definition
> change to cnn model

- terraform/development/main.tf
- terraform/modules/services/forecast/ecs.tf
- terraform/modules/services/forecast/variables.tf
give pv database secret to forecast
Fixes #
> give forecats access to pv datbase

- terraform/modules/services/data_visualization/eb.tf
increase storage size for data-vis
Fixes #
normal checks
> up storage to 22GB

- terraform/modules/services/gsp/schedule.tf
Fix #97
Trigger GSP consumer a few minutes apart to get non-national GSP as well
Fixes #97
> Run GSP trigger again

- terraform/modules/services/gsp/schedule.tf
Relates to #97 but the 2 minute delay in #98 doesn't seem quite long enough, so this ups it to 5 minutes later.
Fixes #
> Update schedule for second GSP pull

- terraform/development/main.tf
- terraform/modules/services/pv/ecs.tf
- terraform/modules/services/pv/iam.tf
- terraform/modules/services/pv/secrets.tf
- terraform/modules/services/pv/variables.tf
add solar Sheffield consumer
Fixes #
ran terraform plan
run task in ecs already
> Two pv consumers

- terraform/modules/services/sat/ecs.tf
> Up memory for sat container

- terraform/modules/services/sat/ecs.tf
> Update CPU to have valid config

- terraform/modules/services/gsp/ecs.tf
- terraform/modules/services/gsp/schedule.tf
Run 
- GSP national at 10.30 local time
- GSP all at 11.30 local time
Fixes #
> Gps national only

- terraform/modules/database/rds.tf
Update database to postgres 14.4
Fixes #
CI
> Postgres 14.4

- terraform/production/main.tf
- terraform/production/variables.tf
add metrics service
Fixes #
test on development
> add metric service to production

- terraform/development/main.tf
- terraform/modules/services/api/docker-compose.yml
- terraform/modules/services/api/eb.tf
- terraform/modules/services/api/variables.tf
Add 2 days of data in dev api
Fixes #
API tested code
> add N_HISTORY_DAYS in api

- terraform/modules/services/api/variables.tf
- terraform/modules/services/data_visualization/s3.tf
- terraform/modules/services/forecast/ecs.tf
- terraform/modules/services/sat/ecs.tf
- terraform/modules/services/sat/schedule-iam.tf
- add satelitle clean up service
- add raw native file dir to satellite consumer
Fixes #
tested on dev
> Sat conusmer upgrade

- terraform/development/main.tf
- terraform/development/variables.tf
- terraform/production/main.tf
- terraform/production/variables.tf
add variables for api for auth
Fixes #
test on dev first
> allow api auth varibles to be set

- terraform/modules/services/pv/ecs.tf
- terraform/modules/services/pv/secrets.tf
add secret to PVConsumer
ran terraform plan in CI
> add secret

- terraform/modules/services/pv/iam.tf
fix to pv ss task can read pv site secret
> allow access to read pv site database secret

- terraform/modules/services/api_pvsite/eb.tf
- terraform/modules/services/api_pvsite/iam.tf
- terraform/modules/services/api_pvsite/variables.tf
- terraform/pvsite/development/main.tf
Add DB_URL to pv site api
Fixes #162 
CI - terraform valid and plan
> add db_url to pv-site-api

- terraform/modules/services/api_pvsite/eb.tf
- terraform/modules/services/api_pvsite/variables.tf
- terraform/pvsite/development/main.tf
add database url to pv sites
Fixes #
CI terraform plan
> update to pass url into api for sites

- terraform/nowcasting/development/main.tf
Adds S3 bucket for Tom to store national forecaster models
> Add S3 bucket for Tom's model storage to nowcasting dev

- terraform/nowcasting/development/main.tf
update ml bucket in national forecast
terraofmr plan locally, and CI terraform
> update ml bucket in national forecast

- terraform/modules/storage/postgres/rds.tf
- terraform/pvsite/development/provider.tf
- terraform/pvsite/production/provider.tf
Add gp3 storage type on pv sites database
Simon checks this manually and it improved the database
> add storage_type gp3 for rds database

- terraform/modules/services/api/docker-compose.yml
- terraform/modules/services/api/eb.tf
- terraform/modules/services/api/variables.tf
- terraform/nowcasting/development/main.tf
add adjust limit on api, deafult is zero
> add adjust limit on api

- terraform/modules/storage/database-pair/rds.tf
- terraform/nowcasting/development/provider.tf
- terraform/nowcasting/production/provider.tf
storage type gp3
Fixes #
terraform CI
> storage type gp3

- terraform/modules/storage/database-pair/rds.tf
- terraform/modules/storage/postgres/rds.tf
Trying to get ahead of param group issues: https://github.com/hashicorp/terraform-provider-aws/issues/6448
> Add lifecycle to param groups

- terraform/modules/services/forecast_generic/ecs.tf
- terraform/modules/services/forecast_generic/variables.tf
- terraform/nowcasting/development/main.tf
- terraform/pvsite/development/main.tf
- terraform/pvsite/production/main.tf
add cpu option in forecast generic
Fixes #
CI
> Cpu forecast option

- terraform/nowcasting/development/main.tf
Move Nationa Forecast mem up to 8 GB
Fixes #
CI tests, and ran this manually in ECS and it worked
> 8GB national forecast mem

- terraform/modules/services/database_clean_up/README.md
- terraform/modules/services/database_clean_up/cloudwatch.tf
- terraform/modules/services/database_clean_up/ecs.tf
- terraform/modules/services/database_clean_up/iam.tf
- terraform/modules/services/database_clean_up/schedule-iam.tf
- terraform/modules/services/database_clean_up/schedule.tf
- terraform/modules/services/database_clean_up/variables.tf
- terraform/pvsite/development/main.tf
- terraform/pvsite/development/variables.tf
Add database clean up service
Fixes #205 
CI plan
> add database clean up fore site forecast

- terraform/modules/services/api_pvsite/docker-compose.yml
- terraform/modules/services/api_pvsite/eb.tf
- terraform/modules/services/api_pvsite/variables.tf
- terraform/pvsite/development/main.tf
Pass through the auth0 variables for pvsite dev.
> Add authorization variables to pvsite dev

- terraform/modules/services/api/docker-compose.yml
- terraform/modules/services/api/eb.tf
- terraform/modules/services/api_pvsite/docker-compose.yml
- terraform/modules/services/api_pvsite/eb.tf
Add ENVIORNMENT to env-vars
Fixes #
CI tests
> add env to api for sentry

- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
> Add internal UI modules (#222)

- terraform/modules/services/gsp/schedule.tf
> run national at 11

- terraform/modules/services/metrics/schedule.tf
> Update metrics schedule to run at midnight

- terraform/modules/services/metrics/schedule.tf
update metrics run time
Fixes #https://github.com/openclimatefix/internal_ui/issues/15
CI terraform tests
> update metrics to at 22 not midnight

- terraform/modules/services/metrics/schedule.tf
Fix: run at 22:00 not 00:22
CI test for terraform
> Update metrics run time

- terraform/modules/services/metrics/schedule.tf
- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
Add pvnet 2.0 to development
It will run every 15 and 45 minutes, we might want to update this later
#243 
Current running by kicking on AWS ECS tasks, to see if it works. This is being done by @dfulu
> add pvnet2.0 to development

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
increase memory for national foreacst
Test it by running AWS task and it worked
> increase memory for national forecast to 10GB

- terraform/nowcasting/development/main.tf
- update docker image location for `analysis dashboard`
CI test
> update docker image location

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
Update production analysis dashbaord
Fixes #
Tested it on dev
> Issue/update internal UI

- terraform/nowcasting/production/main.tf
turn off adjuster on production for pvnet2.01
CI test
> dont use pnet adjuster right now

- terraform/modules/services/sat/ecs.tf
Save more satellite data
Helps with https://github.com/openclimatefix/PVNet/issues/35
CI test
> save 2 hour of satellite data

- terraform/pvsite/production/main.tf
- terraform/pvsite/production/variables.tf
Add database clean up to pro
copied over from dev
CI tests
> add database clean up on pro

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
Up memoery for forecast national. This is with the new xg boost model for probabliilt.
Fixes #
Tested it on dev
> update memory in for forecast national

- terraform/nowcasting/production/main.tf
Turn on PVnet adjuster
Tested on dev
> tune adjuster on

- terraform/modules/services/airflow/dags/forecast-gsp-dag.py
- terraform/modules/services/airflow/dags/forecast-national-dag.py
Add forecast blend into airflow DAGS
Fixes #
uploaded the files to s3 and tested them - they work
> add blend to forecasts dags

- terraform/airflow/production/main.tf
- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
- terraform/pvsite/production/main.tf
- upgrade airflow 
- airflow runs site tasks
- airflow runs blend module
Fixes #
tested in dev
> Upgrade prod

- terraform/modules/services/nwp/ecs.tf
Update for new consumer
- update memory
- change secrets
- change envs
- update docker image
Fixes #
Tested it on ECS manually
> update for new consumer

- terraform/modules/services/nwp/ecs.tf
- terraform/modules/services/nwp/variables.tf
- terraform/nowcasting/development/main.tf
Fixes nwp-national writing to the wrong place.
> Update nwp-consumer task to explicitly pass in command

- terraform/modules/services/internal_ui/docker-compose.yml
- terraform/modules/services/internal_ui/eb.tf
- terraform/modules/services/internal_ui/iam.tf
- terraform/modules/services/internal_ui/secrets.tf
- add pvsite secret to dashboard
- had to import the secret using 'data' which isnt particular pretty
CI tests
> add pvsite secret to internal dashboard

- terraform/modules/storage/s3-trio/s3.tf
Remove raw s3 files from satellite s3 bucket
Fixes #294 
Worked in other s3 buckets
> remove raw sat data

- terraform/modules/storage/s3-trio/s3.tf
Remove 1 week nwp data for national call.
Ci checks
> remove old data in nwp bucket

- terraform/modules/services/internal_ui/docker-compose.yml
- terraform/modules/services/internal_ui/eb.tf
- terraform/modules/services/internal_ui/variables.tf
- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
- Add auth0 to OCF Dashboard
- only doing this on dev env, as will do pro another time
CI tests
> add auth variables to internal ui

- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
Add auth0 to production
- CI 
- added to dev first and works
> add auth0 to dashboard

- terraform/modules/services/airflow/README.md
- terraform/modules/services/airflow/eb.tf
Airflow ran out of storage and crashed. Increase allocated disk storage to 16GB from 8.
#308
> Increase size of Airflow EB env

- terraform/modules/services/airflow/docker-compose.yml
- terraform/modules/storage/database-pair/output.tf
- terraform/modules/storage/database-pair/secrets.tf
- terraform/nowcasting/development/main.tf
airflow tweaks
CI tests, and checked manually
> upgrade airflow url

- terraform/india/development/main.tf
- terraform/modules/ecs_cluster/iam.tf
- terraform/modules/ecs_cluster/variables.tf
- terraform/modules/services/airflow/iam.tf
- terraform/modules/services/airflow/variables.tf
- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
- terraform/pvsite/development/main.tf
Removes hardcoding of the secretsmanager instance ID in preference of variable
> Pass secretsmanager instance name in as environment variable

- terraform/nowcasting/production/main.tf
- add NWP ECMWF
- use execution role in GSP ECS task, using the cluster execution role
- updates generic forecast to use env var for ml model s3 bucket
- updates nwp consumer module, built ready for ecmwf
- Updates networking module to make new output
> Update prod to use dev modules

- terraform/modules/storage/database-pair/rds.tf
- terraform/modules/storage/s3-trio/s3.tf
> Update deprecated modules

- terraform/modules/services/airflow/dags/utils/slack.py
- terraform/modules/services/airflow/s3.tf
updater air flow channle name from `airflow-alerts-development` to `tech-ops-ariflow-development`
CI tests
> update slack channle name for airflow alerts

- terraform/nowcasting/production/main.tf
Update production slack name
test on development first
CI tests
> airflow production to 01854a6, update for channel name

- terraform/modules/services/airflow/dags/forecast-gsp-dag.py
- reduce pvnet 1 to run every 4 hours
Fixes #306 
CI tests
> reduce pvnet-1 to only run every 4 hours

- terraform/nowcasting/production/main.tf
Update production airflow
- increase national forecast retries from 1 to 2
- rename some workflows (fix)
ran on dev
> upgrade airflow

- terraform/modules/services/pv/ecs.tf
- terraform/modules/services/pv/secrets.tf
only pull pv data from sheffield solar in the PVConsumer
CI tests
> only pull pv data from sheffield solar

- terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
- terraform/modules/services/api/eb.tf
- terraform/modules/services/api/iam.tf
- terraform/modules/services/api/variables.tf
- terraform/modules/services/pv/ecs.tf
- terraform/modules/services/pv/variables.tf
- terraform/modules/storage/database-pair/README.md
- terraform/modules/storage/database-pair/iam.tf
- terraform/modules/storage/database-pair/output.tf
- terraform/modules/storage/database-pair/rds.tf
- terraform/modules/storage/database-pair/secrets.tf
- terraform/nowcasting/development/main.tf
- remove old pv database
- update pv consumer
- update api
- remove pvnet 1
Fixes #377 
CI test
> rm old pv database

- terraform/india/development/main.tf
- terraform/modules/services/eb_app/README.md
- terraform/modules/services/eb_app/eb.tf
- terraform/modules/services/eb_app/iam.tf
- terraform/modules/services/eb_app/output.tf
- terraform/modules/services/eb_app/s3.tf
- terraform/modules/services/eb_app/security_group.tf
- terraform/modules/services/eb_app/variables.tf
- terraform/nowcasting/production/variables.tf
Adds the India API to the india platform. Uses a new, generic Elastic Beanstalk module.
> Add API to india development

- terraform/india/development/readme.md
add india readme
Helps with #400 
Looked at it locally
> add india readme

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
- terraform/modules/services/airflow/dags/india/forecast-site-dag.py
- terraform/modules/services/forecast_generic/variables.tf
- Add forecast ECS task definition
- add Airflow task
Fixes #407 
- terraform CI
- might have to just push it thorugh and test it out for real
> add forecast for india

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
- terraform/modules/services/airflow/dags/india/runvnl-data-dag.py
- terraform/modules/storage/postgres/rds.tf
Run RUVNL dataconsumer,
- Add service using `nwp_consumer` to reduece duplciate code
-  add dag
- upgraded postgres to 15.5, as thats what the inidia database is already. 
Follows from https://github.com/openclimatefix/ruvnl-consumer-app/pull/1
terraform CI
> first try and ruvnl data consumer

- terraform/modules/storage/database-pair/rds.tf
pg database 15.5
Fixes #
CI tests
>   engine_version               = "15.5"

- terraform/nowcasting/production/main.tf
upgrade database to 15.5, (they have already been done in fact)
Done on dev
and CI tests
> upgrade databases - 2747e85

- terraform/modules/networking/main.tf
> fix name for private subnet

- terraform/modules/services/airflow/eb.tf
update docker version for airflow
> update docker version for airflow

- terraform/modules/storage/s3-private/bucket.tf
Uses dynamic for making several life cycles rules in a new bucket
#422 
CI tests, look in the terraform plan
> change to use dynamic rules

- terraform/india/development/main.tf
- terraform/modules/services/nwp_consumer/ecs.tf
- terraform/modules/services/nwp_consumer/variables.tf
> tidy up nwp-consumer cpu and memory

- terraform/nowcasting/development/main.tf
Use data-national NWP, which has 36 hours for NWP
Fixes #426 
tested by adjusting AWS ecs tasks
> use data-national for nwp

- terraform/india/development/main.tf
- terraform/modules/services/eb_app/eb.tf
- change india api to use real database
- add env variables to india api
Fixes #
CI tests
> add container variables to eb_api

- terraform/nowcasting/production/main.tf
Update NWP data on production site forecast
Fixes #426 
Tested on dev
> nwp data-national on production

- terraform/modules/storage/database-pair/rds.tf
- terraform/modules/storage/postgres/rds.tf
* Fixes upgrade rds postgres to 16.1 #383
* Fixes missing files on upgrade rds postgres to 16.1 #383
---------
- upgrade RDS to 16.1
Fixes #
CI tests
> Issue/upgrade rds postgres 16 1 (#435)

- terraform/modules/services/nwp_consumer/variables.tf
- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
up nwp memory size
update order name
> Fix nwp national

- terraform/india/development/main.tf
- terraform/modules/storage/database-pair/rds.tf
- terraform/modules/storage/database-pair/variables.tf
- terraform/modules/storage/postgres/rds.tf
- terraform/modules/storage/postgres/variables.tf
- add options for rds engine version, means we can control the version per project
Helps with https://github.com/openclimatefix/ocf-infrastructure/issues/383
CI tests
> add options to rds, engine_version

- terraform/modules/services/api_pvsite/eb.tf
> change eb tags

- terraform/modules/services/eb_app/eb.tf
- terraform/modules/services/eb_app/s3.tf
- terraform/modules/services/eb_app/variables.tf
- terraform/nowcasting/development/main.tf
change api sites to use eb_app
Helps with #444 
CI tests, check that nothign is too different
> change api sites to use eb_app

- terraform/modules/services/airflow/dags/india/nwp-dag.py
> fix(NWP dag): not running

- terraform/nowcasting/production/main.tf
Just updates dasboard
splits out #452 
- done on dev
- CI tests
> upgrade dashbaord

- terraform/india/development/main.tf
Update india forecast
Fixes #
Tested it manually in AWS console
> update india foreacst

- terraform/nowcasting/development/README.md
> rm pvnet1 from Readme in nowcasting/development

- terraform/nowcasting/production/README.md
> rm pvnet1 from Readme in nowcasting/production

- terraform/modules/services/forecast_generic/ecs.tf
- add variables to forecast_generic for pvnet. Add NWP_UKV_ZARR_PATH and NWP_ECMWF_ZARR_PATH
This is needed with https://github.com/openclimatefix/pvnet_app/pull/48
> add variables to forecast_generic

- terraform/nowcasting/production/main.tf
Fix production branch, to do with remove a variable
CI tests
> upgrade pv version

- terraform/modules/services/eb_app/iam.tf
- terraform/modules/services/eb_app/variables.tf
- terraform/nowcasting/development/main.tf
Give analysis dashbaord access to nwp s3 bucket
Fixes #
CI tests
> add s3 nwp read to eb_application

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
add india analysis dashboard
Helps with  https://github.com/openclimatefix/uk-analysis-dashboard/issues/114
CI tests
> add analysis dashboard for india

- terraform/nowcasting/production/main.tf
Fix site api,
Fixes #
use same version as app and dashboard
> update pvsite api version

- terraform/nowcasting/production/main.tf
Update PVnet production for ECMWF variables
tested on dev
> upgrade to 7678388, pvnet

- terraform/nowcasting/production/main.tf
Update airflow for PVnet. This adds in ECMWF consumer
tests on development
> Ecmwf production

- terraform/nowcasting/production/main.tf
Get nwp consumers to run at the same time
Deployed on Dev already
> upgrade airflow to 1af4f8a

- terraform/india/development/main.tf
- terraform/modules/user_groups/main.tf
- terraform/modules/user_groups/variables.tf
Created to run checks on changes authored by @aryanbhosale in order to merge into main. See https://github.com/openclimatefix/ocf-infrastructure/pull/496.
> Add development user group

- terraform/india/production/main.tf
- terraform/modules/services/airflow/docker-compose.yml
Returns airflow india in prod to the commented airflowinit docker compose file.
> chore(india prod): Airflow module bump

- terraform/india/development/main.tf
- terraform/modules/services/eb_app/iam.tf
- terraform/modules/services/eb_app/variables.tf
- terraform/nowcasting/development/main.tf
- add satellite bucket to analysis dashaord
- refactor s3_nwp_bucket to s3_bucket
CI tests
> refactor and add satellite to internal dashboard

- terraform/modules/services/airflow/dags/india/forecast-site-dag.py
- terraform/modules/services/airflow/dags/india/nwp-dag.py
- terraform/modules/services/airflow/dags/india/runvnl-data-dag.py
- terraform/modules/services/airflow/dags/uk/dayafter-dag.py
- terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
- terraform/modules/services/airflow/dags/uk/forecast-national-dag.py
- terraform/modules/services/airflow/dags/uk/forecast-site-dag.py
- terraform/modules/services/airflow/dags/uk/gsp-dag.py
- terraform/modules/services/airflow/dags/uk/nwp-dag.py
- terraform/modules/services/airflow/dags/uk/pv-dag.py
- terraform/modules/services/airflow/dags/uk/satellite-dag.py
Added region (india/uk) in their respective directories under airflow at the beginning of DAG to make error detection streamlined
Fixes #
#522
> added region name(uk/india) at the beginning of DAG

- terraform/modules/services/airflow/dags/india/forecast-site-dag.py
- terraform/modules/services/airflow/dags/india/nwp-dag.py
- terraform/modules/services/airflow/dags/india/runvnl-data-dag.py
- terraform/modules/services/airflow/dags/uk/dayafter-dag.py
- terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
- terraform/modules/services/airflow/dags/uk/forecast-national-dag.py
- terraform/modules/services/airflow/dags/uk/forecast-site-dag.py
- terraform/modules/services/airflow/dags/uk/gsp-dag.py
- terraform/modules/services/airflow/dags/uk/nwp-dag.py
- terraform/modules/services/airflow/dags/uk/pv-dag.py
- terraform/modules/services/airflow/dags/uk/satellite-dag.py
This builds on #525 after a suggestion given by @peterdudfield [here](https://github.com/openclimatefix/ocf-infrastructure/issues/522#issuecomment-2070858580), this is the corrected version of #526 where i'd accidentally changed the task definitions too
Fixes #
it fixes #522
> Added region to task_ids

- terraform/india/production/main.tf
- terraform/nowcasting/production/main.tf
Update production airflow to include regions in task_id. This means in slack its clear what service (and region) has failed
#522 
Tested on dev
> upgrade airflow, task id include region

- terraform/modules/services/eb_app/eb.tf
Add resouce to eb app, should get rid of terraform extra deployments
This works for airflow app
> add resource=""

- terraform/india/production/main.tf
- terraform/nowcasting/production/main.tf
Update eb-app (APIs and dashbaord) 
Update databases, new license #453 
Tested on dev
> update production of eb-app and rds

- terraform/india/development/main.tf
- terraform/modules/services/eb_app/iam.tf
Update internal UI, tried to add nwp read policy to indai
CI tests, can see it adds thepolicy
> Fix IAM policyes for eb_app

- terraform/india/development/main.tf
Increase forecast memory.
Following on from https://github.com/openclimatefix/india-forecast-app/pull/72
Fixes #
CI test and tested locally
> india - forecast    memory_mb      = 3GB

- terraform/nowcasting/production/main.tf
Add nwp and satellite read to dashbaord
Fixes #
Tested on dev first
> update dashboard, access to nwp and satellite

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
- terraform/modules/services/eb_app/variables.tf
- terraform/modules/services/forecast_generic/ecs.tf
- terraform/modules/services/forecast_generic/variables.tf
add sentry dsn to india forecast
Fixes #
terraform CI plan
> add sentry dsn to forecast india app

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
add auth enviornmental variables to india api, needed for https://github.com/openclimatefix/india-api/pull/54
CI tests
> add auth to india api

- terraform/india/production/main.tf
- terraform/india/production/variables.tf
Add auth variables to production api
Tested on dev alread
> add auth variables to india api

- terraform/modules/storage/database-pair/variables.tf
> upgrade database

- terraform/modules/storage/postgres/variables.tf
Change pv site database to 16.3 (from 15.5.)
Already done manually, just need to do this in terraform
> pv site database to 16.3

- terraform/india/development/main.tf
- terraform/modules/services/airflow/dags/india/nwp-dag.py
Adds GFS live consumer to india development environment
> feat(india-dev): Add GFS consumer

- terraform/modules/services/airflow/dags/uk/forecast-national-dag.py
Reduce national-xg to run every 2 hours at 15 mins past
Fixes #572 
CI tests
> run national-xg only eveyr 2 hours

- terraform/nowcasting/production/main.tf
Update to new name of analysis dashbaord
CI and worked on dev
> update dashboard repo

- terraform/india/development/main.tf
Changes GFS consumer to only try to download the last run, not all runs in the day
> fix(gfs): Modify from argument

- terraform/modules/services/forecast_generic/ecs.tf
This PR includes a change to add in an environment variable for the GFS NWP in the India dev environment, this is to support [this change](https://github.com/openclimatefix/india-forecast-app/pull/82) in the india forecast app
> Add GFS NWP zarr path

- terraform/india/production/main.tf
- add gfs for india
- update forecast inf version, so GFS env var is there
This does not deploy the latest forecast docker version
CI test + deployed on dev
> update india production, with gfs consumer

- terraform/india/production/main.tf
Update airflow so gfs runs
Fixes #
CI tests and tested on dev
> Gfs production

- terraform/modules/services/airflow/dags/uk/forecast-national-dag.py
Fix to get national xg running again eveyr 2 hours
Fixes #
CI tests
> fix to make national xg run

- terraform/india/development/main.tf
Add s3 bucket for satellite
Need this first before #587
> add satellite s3 bucket

- terraform/india/development/main.tf
import satellite secret
Fixes #
CI tests
> import secret

- terraform/india/development/main.tf
Add read access for india dashbaord to satellite bucket
Fixes #
CI tests, similar to UK also
> add satellite read policy to dashboard

- terraform/india/production/main.tf
Add satellite s3 bucket
CI tests + did this in development
> add s3 satellite bucket

- terraform/india/development/main.tf
Add region to env to india dashboard
helps https://github.com/openclimatefix/analysis-dashboard/issues/189
CI tests
> add region and env to india dashboard

- terraform/india/production/main.tf
- terraform/india/production/variables.tf
Add satellite consumer
- add satellite bucket (done in #592 )
- add satellite consumer 
- add read access to satellite bucket for forecast
- add satellite secret (values added manully to AWS)
- add airflow dag to trigger satellite consumer
Helps with https://github.com/openclimatefix/Satip/issues/279
Works on dev
> add satellite to india production

- terraform/modules/services/airflow/dags/india/satellite-dag.py
India satellite increase retries, to increase resilience. 
CI tests
> change satellite retries from 1 to 2

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
Add sentry dsn backend to pvnet
#540 
CI tests
> add sentry dsn backend to pvnet

- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
Tidy up sentry on sites api
Ci tests
> mvoe sites api sentry onto same dsn

- terraform/india/production/main.tf
- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
Add region and envrionment to uk and india dashbaords
Helps with https://github.com/openclimatefix/analysis-dashboard/issues/189
CI test + tested on dev on india platform
> add region and environment to all other dashboards

- terraform/india/production/main.tf
upgrade satellite for india, so that retreis=2 on ariflow
Tested this on dev and it helped reduce errors
> upgrade india airflow - retries for satellite =2

- terraform/india/development/main.tf
Add hugging face secret to terraform
- added a temporary import statement
Fixes #604 
CI tests
> add secret for huggingface #604

- terraform/india/development/main.tf
- terraform/modules/services/airflow/dags/india/forecast-site-dag.py
fix ECS and airflow task names
Fixes #
CI test
> match up ECS and airflow tasks

- terraform/india/development/main.tf
- terraform/modules/services/airflow/docker-compose.yml
- terraform/nowcasting/development/main.tf
always restart scheduler
+ bump versions
CI tests
> restart always

- terraform/india/development/main.tf
Update india development database
CI test
> india rds 16.3

- terraform/india/development/main.tf
Add satip variables to india satellite consumer
Helps with #540 
CI tests
> add sentry dsn and evn to satip india

- terraform/nowcasting/development/main.tf
add sentry to metrics
CI tests
> add sentry to metrics

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
- terraform/india/production/main.tf
- terraform/india/production/variables.tf
Add sentry to india api
CI tests
> add sentry to india api

- terraform/modules/services/airflow/dags/india/forecast-site-dag.py
Add specific name suffixes to india forecast DAGs for improved alerting/visibility
> Add name suffix to india forecast dags

- terraform/india/production/main.tf
Updating git hash for airflow india prod to latest
> Update git hash for airflow

- terraform/india/production/main.tf
Add sentry to India production
Helps with #540 
Ci tests
> add sentry to india production stack

- terraform/nowcasting/production/main.tf
The current RDS version is 15.7, and we getting weird bugs trying to role it back.
This should fix things
Note this doesnt cause any changes in the database, just stops the terraform cloud bug
CI tests
> pin uk db version

- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
Add sentry dsn to uk production
Fixes #
CI tests
> add sentry dsn

- terraform/nowcasting/production/main.tf
- Update gsp consumer to seperate ecs task
- add sentry in
Helps with #540 
- CI tests
- deployed on dev for > 1 week
> GSP consumer uk pro + sentry

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
- change satellite to ecs task
- add sentry to satellite tasks
Helps with #540 
Ci tests
ran this on dev > 1 week
> change satellte to ecs + add sentry

- terraform/nowcasting/production/main.tf
> fix sat secret name

- terraform/nowcasting/production/main.tf
> import sat secret

- terraform/india/development/main.tf
- terraform/india/production/main.tf
- terraform/modules/services/ecs_task/ecs.tf
- terraform/modules/services/ecs_task/variables.tf
- terraform/nowcasting/development/main.tf
Remove volume for ecs task
Pin india forecast ad to git version
Might help https://github.com/openclimatefix/nwp-consumer/issues/189
CI tests
> clean up ecs task

- terraform/nowcasting/development/main.tf
Use new ocf data sampler models in pvetn on dev uk
Fixes #
CI tests
> use ocf data sampler in pvnet dev

- terraform/india/development/main.tf
Enables the consumer to pull the new whole-india data provided by ECMWF.
Must coincide with an update to consumer version >= 0.5.30.
> fix(main): Update ECMWF consumer env

- terraform/india/production/main.tf
Propagate realtime data changes through to prod
> feat(india-prod): Update consumer to use new realtime data

- terraform/india/production/main.tf
Run adani forecast every 30 mins
#643 
Tested out on dev already
> run adani every 30

- terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
Run pvnet at 6.45 not 6.15
#659 
CI tests
> run da at 45 instead

- terraform/nowcasting/production/main.tf
Upgrade pro pvnet da to run at */45
#659 
CI test + ran on dev
> upgrade airflow, pvnet 45

- terraform/nowcasting/development/main.tf
import pv secret in main.tf
Fixes #
CI tests
> get PV secret

- terraform/modules/services/airflow/dags/india/elasticbeanstalk.py
- terraform/modules/services/airflow/dags/uk/elasticbeanstalk.py
- terraform/modules/services/airflow/dags/utils/elastic_beanstalk.py
- terraform/modules/services/airflow/iam.tf
Rotate ec2 elastic beasntalk instances, once a month
#670
> Rotate ec2 instances in elastic beanstalk

- terraform/nowcasting/production/main.tf
- upgrade module
- upgrade s3 link
- upgrade s3 life cycles
- upgrade airflow dag
This fixes
#469 
Tested for +24 hours on development, no errors on forecasting
> Nwp metoffice produ

- terraform/nowcasting/development/main.tf
Fix site database clean up, get secret right
CI tests
> fix site secret

- terraform/modules/services/airflow/dags/uk/nwp-dag.py
> fix nwp file

- terraform/india/development/main.tf
- terraform/modules/services/airflow/dags/india/nwp-dag.py
- terraform/modules/services/airflow/dags/utils/s3.py
- terraform/modules/services/airflow/eb.tf
Adds an ECS task to pull mettofice data for India.
> Create ECS task for india metoffice data

- terraform/india/production/main.tf
- add mo nwp consumer
- update airflow
- update forecast ru
CI tests, and tested on development
> add nwp mo, upgrade ariflow and forecast ru

- terraform/india/production/main.tf
Bumping the memory for the RU forecast app in prod
> Increase memory for ru forecaster prod

- terraform/india/development/main.tf
- change RUNVL forecast to ecs task
- add s3 bucket for forecast
- add s3 bucket SAV_BATCHES_DIR to both india forecasts
[Fixes #](https://github.com/openclimatefix/india-forecast-app/issues/114)
CI tests
> add s3 bucket, add to forecast, move foreacst ruvnl to ecs task

- terraform/nowcasting/development/main.tf
Change PVnet DA to us ecs-task
CI tests
> change pvnet da to ecs-task

- terraform/nowcasting/development/main.tf
Change PVnet to use ecs_task
CI tests
> change pvnet to use ecs_task

- terraform/nowcasting/development/main.tf
clean ups for changing forecast_generic to ecs_task
CI tests
> National xg ecs task

- terraform/modules/storage/open-data-pvnet-s3/bucket.tf
- terraform/modules/storage/open-data-pvnet-s3/iam.tf
- terraform/nowcasting/development/main.tf
Add
- s3 public bucket
- IAM user group that can write to the bucket
Helps with https://github.com/openclimatefix/open-data-pvnet/issues/11
CI tests
> Add Open Data Pvnet

- terraform/nowcasting/production/main.tf
Upgrade database from 200 GB to 300 GB, 
#719 
Tested on dev first
> upgrade rds database

- terraform/nowcasting/production/main.tf
Upgrade api to t3.medium, this has more cpu and more ram,
Fixes #
CI tests
> Upgrade api to t3.medium

- terraform/india/production/main.tf
- terraform/nowcasting/production/main.tf
Run Adani forecast every 15 mins
CI tests + run on dev
> upgrade adani airflow

- terraform/nowcasting/production/main.tf
- update airflow
- update ecs task for pvlive
- Note, when appliying this need to bump to gsp_version=1.2.4
#709 
Tested on dev
> change to use pvlive

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
- terraform/modules/services/airflow/dags/india/nwp-dag.py
Use new nwp consumer in India
Helps with #697
> use latest nwp consumer ecmwf india

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
- terraform/modules/services/airflow/dags/india/nwp-dag.py
Tidy up NWP ECMWF india
Fixes #
CI tests
> New consumer ecmwf india

- terraform/india/development/main.tf
Save 75 minutes of satellie data
This helps https://github.com/openclimatefix/india-forecast-app/issues/168
Tested it with ECS
> sat history 60 --> 75 minutes

- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
Update production PVetn DA to use ecs-task. Then lastest version pvnet app can be used.
CI tests
Copied from dev
> Uk ecmwf new consumer

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/production/main.tf
Add ENVIRONMENT to dev and pro api
This helps Sentry
CI tests
> add env to api on dev and pro

- terraform/modules/services/airflow/dags/uk/nwp-dag.py
look for latest.zarr, not latest.zarr.zip
#740 
CI tests
> look for latest.zarr not latest.zarr.zip

- terraform/modules/storage/database-pair/variables.tf
- terraform/modules/storage/postgres/variables.tf
Update SQL db to 16.6
#742 
CI tests
> update database to 16.6

- terraform/nowcasting/development/main.tf
#745 
_Added `SAVE_BATCHES_DIR` environment variable and write policy for `module.forecasting_models_bucket.bucket_id`._
> Save batches

- terraform/nowcasting/development/main.tf
Buld on #747 and run CI
Fixes #
Ci tests
> Save batches (#747)

- terraform/nowcasting/development/main.tf
Add write policy for PVnet
Fixes #
Ci tests
> add write policy for pvnet forecast

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
Move all version to nwp-version for the NWP consumers
#291 
Already running on dev
> move all nwp version to version-nwp

- terraform/nowcasting/development/main.tf
Using data-sampler in development
> Update to development/main.tf

- terraform/nowcasting/production/main.tf
Upgrade UK ariflow to show AWS cloudwatch logs
#756  
Tested on dev
> upgrade airflow to 631a791

- terraform/india/development/main.tf
- terraform/india/production/main.tf
- terraform/modules/storage/s3-trio/s3.tf
- terraform/nowcasting/production/main.tf
Tidy up s3 buckets for
- india development
- india production
- uk development
CI tests
> remove s3 files after 7 days

- terraform/modules/services/airflow/dags/uk/satellite-dag.py
- Add a specific message for satellite
CI tests and ran manulaly
> sat specific message

- terraform/nowcasting/production/main.tf
Copied over from dev
- change forecast_pvnet to use ecs task,  (made sure its using the old ocf-datapipes models)
- Updated Blend model too
#777
On dev
> change forecast_pvnet to use ecs task, and change blend to use ecs_task

- terraform/modules/services/airflow/dags/india/nwp-dag.py
switched GFS and ECMWF error message as mentioned in the [issue](https://github.com/openclimatefix/ocf-infrastructure/issues/785)
Fixes #
> switched GFS and ECMWF error message

- terraform/modules/services/airflow/eb.tf
This PR increases the Airflow Volume to 32GB. Was 16GB.
Fixes #796 
No testing carried out.
Does not affect data processing.
> Increase Airflow Storage to 32GB

- terraform/nowcasting/production/main.tf
Change PVnet to use ghcr.io, not for DA. 
similar to dev
> use ghcr.io for pvnet

- terraform/modules/services/airflow/dags/uk/sat-dag.py
- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
Adds the new satellite consumer, running in a test bucket for now, and an airflow dag to run it.
> feat(nowcasting-dev): Add satellite-consumer and airflow dag

- terraform/modules/services/airflow/dags/uk/pvlive-dag.py
Change :warning to ⚠️ in slack message
CI tests
> change icon to warning, pvlive dag

- terraform/modules/services/airflow/dags/uk/forecast-gsp-dag.py
- terraform/nowcasting/development/main.tf
- Update the PVNet UK environmental variables so they are compatible with uk-pvnet-app>=2.5.1
- Remove the ECMWF-only PVNet run. Both the main PVNet model and the ECMWF-only model are run in parallel in a single call of the app
> Update uk-pvnet-app dev env vars

- terraform/india/production/main.tf
- terraform/nowcasting/production/main.tf
Remove dags from production in uk and inda
Ci tests and done on dev
> remove dags from production

- terraform/nowcasting/development/main.tf
Upgrade nwp consumer
TODO - Up Forecast to 10GB
#697
> upgrade nwp ukv

- terraform/nowcasting/production/main.tf
Fix spelling on metrics ecs log group
Ci and on dev
> fix sp on metrics

- terraform/nowcasting/development/main.tf
Add zarrdir in nwp ukv consumer
Might need to copy this over to airflow
Tested on dev
> fix for nwp

- terraform/india/development/main.tf
- terraform/nowcasting/development/main.tf
Since ECS tasks creation has been moved to Airflow, remove the task definitions from terraform.
> refactor(dev): Remove ECS tasks from mains

- terraform/india/production/main.tf
- terraform/nowcasting/production/main.tf
- air IAM permissions
Fixes #
Ci tests and tested on dev
> upgrade prod airflow to a79aaa8

- terraform/india/production/main.tf
- india rds prod, to 17.2
Ci tests
> india database 17.2

- terraform/nowcasting/production/main.tf
update database to 17.2
Might help with metrics taking 4 hours of prod, but 1 hour on dev
Warning, the database needs to be done out of hours, as the migrations can cause some downtime
CI tests
> update databse to 17.2

- terraform/india/development/main.tf
Move rds version to what it is
> 16.8 rds on india dev

- terraform/nowcasting/production/main.tf
> Update ec2 basiton on uk production

- terraform/nowcasting/production/main.tf
- terraform/nowcasting/production/variables.tf
- update uk airflow
- add username and pwd for auth0 in variables
> update ariflow + add auth0 user name and pwd

- terraform/nowcasting/production/main.tf
Upgrade 15.12 postgres rds database
- already deployed, just catching terraform up
> upgrade rds to 15.12

- terraform/modules/storage/database-pair/variables.tf
Update defualt database change from 17.2 to 17.4
> Update rds to 17.4 dev-uk

- terraform/india/production/main.tf
> rds prod india 17.4

- terraform/india/development/main.tf
- terraform/india/development/variables.tf
Add auth0 username and password to airflow india development
> add auth0 variables to airflow

- terraform/india/production/main.tf
- terraform/india/production/variables.tf
Add auth0 variables 
https://github.com/openclimatefix/ocf-infrastructure/issues/875 and https://github.com/openclimatefix/airflow-dags/issues/272
Ran on dev
> add auth0 variables

- terraform/india/production/main.tf
Add read access for dashboard
#883 
- works on dev
- ci tests
> add iam read

- terraform/india/production/main.tf
- terraform/nowcasting/production/main.tf
upgrade airflow, to include URL env
Follows on from #881 
- This is running on dev
> upgrade airflow, to include URL env

- terraform/nowcasting/development/main.tf
let the dashboard read s3 bucket with nl batches in it
Helps with https://github.com/openclimatefix/analysis-dashboard/issues/336
CI tests
> let the dashboard read the s3 bucket with nl batches

- terraform/nowcasting/production/main.tf
Upgrade RDS uk production to 500 GB, actually done this in the AWS console, so just cataching up terraform
- CI tests
> upgrade to 500 GB rds storage

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
Add data platform things
- database on rds
- api on elastic beanstalk
- CI tests
> add dataplatform database and api

- terraform/nowcasting/development/main.tf
- terraform/nowcasting/development/variables.tf
Fix data platform rds databas name
- similar to other database names,
> Data platform
